site_name:           PDMP.jl
repo_url:            https://github.com/alan-turing-institute/PDMP.jl.git
site_description:
site_author:         Thibaut Lienart
theme:               readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
  - mdx_math # For LaTeX

docs_dir: 'src'

edit_uri: edit/master/docs/src

pages:
- Introduction: index.md
# - Tutorial:
#   - Title 1: tutorials/page1.md
#   - Title 2: tutorials/page2.md
#   - Title 3: tutorials/page3.md
# - Another Section:
#   - Title 1: sec2/page1.md
#   - Title 2: sec2/page2.md
#   - Title 3: sec2/page3.md
